{
 "title": "Nebula Dashboard",
 "time": { "from": "2023-08-30T20:55:02.557Z", "to": "2023-08-31T08:55:02.557Z" },
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "label": "datasource", "query": "prometheus" },
   {
    "name": "cluster_id",
    "label": "cluster_id",
    "query": {
     "query": "label_values(node_uname_info,nebula_cluster)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Nebula Metad",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "num_start_elect",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_metad_num_start_elect_rate_5{componentType=\"metad\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_metad_num_start_elect_sum_5{componentType=\"metad\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "commit_snapshot_latency_us",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "nebula_metad_commit_snapshot_latency_us_avg_5{componentType=\"metad\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_avg_5"
      },
      {
       "expr": "nebula_metad_commit_snapshot_latency_us_p95_5{componentType=\"metad\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_p95_5"
      }
     ]
    },
    {
     "title": "num_grant_votes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_metad_num_grant_votes_rate_5{componentType=\"metad\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_metad_num_grant_votes_sum_5{componentType=\"metad\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "commit_log_latency_us",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "nebula_metad_commit_log_latency_us_avg_5{componentType=\"metad\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_avg_5"
      },
      {
       "expr": "nebula_metad_commit_log_latency_us_p95_5{componentType=\"metad\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_p95_5"
      }
     ]
    },
    {
     "title": "append_log_latency_us",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "nebula_metad_append_log_latency_us_avg_5{componentType=\"metad\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_avg_5"
      },
      {
       "expr": "nebula_metad_append_log_latency_us_p95_5{componentType=\"metad\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_p95_5"
      }
     ]
    },
    {
     "title": "num_agent_heartbeats",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_metad_num_agent_heartbeats_rate_5{componentType=\"metad\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_metad_num_agent_heartbeats_sum_5{componentType=\"metad\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "append_wal_latency_us",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "nebula_metad_append_wal_latency_us_avg_5{componentType=\"metad\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_avg_5"
      },
      {
       "expr": "nebula_metad_append_wal_latency_us_p95_5{componentType=\"metad\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_p95_5"
      }
     ]
    },
    {
     "title": "num_send_snapshot",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_metad_num_send_snapshot_rate_5{componentType=\"metad\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_metad_num_send_snapshot_sum_5{componentType=\"metad\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "replicate_log_latency_us",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "nebula_metad_replicate_log_latency_us_avg_5{componentType=\"metad\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_avg_5"
      },
      {
       "expr": "nebula_metad_replicate_log_latency_us_p95_5{componentType=\"metad\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_p95_5"
      }
     ]
    },
    {
     "title": "agent_heartbeat_latency_us",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "nebula_metad_agent_heartbeat_latency_us_avg_5{componentType=\"metad\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_avg_5"
      },
      {
       "expr": "nebula_metad_agent_heartbeat_latency_us_p95_5{componentType=\"metad\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_p95_5"
      }
     ]
    },
    {
     "title": "transfer_leader_latency_us",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "nebula_metad_transfer_leader_latency_us_avg_5{componentType=\"metad\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_avg_5"
      },
      {
       "expr": "nebula_metad_transfer_leader_latency_us_p95_5{componentType=\"metad\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_p95_5"
      }
     ]
    },
    {
     "title": "num_heartbeats",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_metad_num_heartbeats_rate_5{componentType=\"metad\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_metad_num_heartbeats_sum_5{componentType=\"metad\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "heartbeat_latency_us",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "nebula_metad_agent_heartbeat_latency_us_avg_5{componentType=\"metad\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_avg_5"
      },
      {
       "expr": "nebula_metad_agent_heartbeat_latency_us_p95_5{componentType=\"metad\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_p95_5"
      }
     ]
    }
   ]
  },
  {
   "title": "Nebula Storaged",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "sync_data_latency_us",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "nebula_storaged_sync_data_latency_us_avg_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_avg_5"
      },
      {
       "expr": "nebula_storaged_sync_data_latency_us_p95_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_p95_5"
      }
     ]
    },
    {
     "title": "add_vertices_latency_us",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "nebula_storaged_add_vertices_latency_us_avg_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_avg_5"
      },
      {
       "expr": "nebula_storaged_add_vertices_latency_us_p95_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_p95_5"
      }
     ]
    },
    {
     "title": "num_sync_data_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_sync_data_errors_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_sync_data_errors_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_lookup_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_lookup_errors_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_lookup_errors_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_sync_data",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_sync_data_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_sync_data_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "delete_edges_latency_us",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "nebula_storaged_delete_edges_latency_us_avg_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_avg_5"
      },
      {
       "expr": "nebula_storaged_delete_edges_latency_us_p95_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_p95_5"
      }
     ]
    },
    {
     "title": "num_lookup",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_lookup_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_lookup_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "get_neighbors_latency_us",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "nebula_storaged_get_neighbors_latency_us_avg_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_avg_5"
      },
      {
       "expr": "nebula_storaged_get_neighbors_latency_us_p95_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_p95_5"
      }
     ]
    },
    {
     "title": "num_get_prop_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_get_prop_errors_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_get_prop_errors_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "delete_vertices_latency_us",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "nebula_storaged_delete_vertices_latency_us_avg_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_avg_5"
      },
      {
       "expr": "nebula_storaged_delete_vertices_latency_us_p95_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_p95_5"
      }
     ]
    },
    {
     "title": "num_delete_vertices",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_delete_vertices_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_delete_vertices_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "commit_log_latency_us",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "nebula_storaged_commit_log_latency_us_avg_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_avg_5"
      },
      {
       "expr": "nebula_storaged_commit_log_latency_us_p95_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_p95_5"
      }
     ]
    },
    {
     "title": "num_get_neighbors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_get_neighbors_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_get_neighbors_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_get_dst_by_src",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_get_dst_by_src_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_get_dst_by_src_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "delete_tags_latency_us",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "nebula_storaged_delete_tags_latency_us_avg_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_avg_5"
      },
      {
       "expr": "nebula_storaged_delete_tags_latency_us_p95_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_p95_5"
      }
     ]
    },
    {
     "title": "num_update_edge_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_update_edge_errors_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_update_edge_errors_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "append_wal_latency_us",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "nebula_storaged_append_wal_latency_us_avg_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_avg_5"
      },
      {
       "expr": "nebula_storaged_append_wal_latency_us_p95_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_p95_5"
      }
     ]
    },
    {
     "title": "num_update_edge",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_update_edge_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_update_edge_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_send_snapshot",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_send_snapshot_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_send_snapshot_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "update_vertex_latency_us",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "nebula_storaged_update_vertex_latency_us_avg_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_avg_5"
      },
      {
       "expr": "nebula_storaged_update_vertex_latency_us_p95_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_p95_5"
      }
     ]
    },
    {
     "title": "num_delete_edges",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_delete_edges_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_delete_edges_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_delete_edges_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 82 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_delete_edges_errors_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_delete_edges_errors_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_delete_tags",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_delete_tags_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_delete_tags_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_delete_tags_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 90 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_delete_tags_errors_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_delete_tags_errors_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_grant_votes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_grant_votes_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_grant_votes_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "replicate_log_latency_us",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 98 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "nebula_storaged_replicate_log_latency_us_avg_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_avg_5"
      },
      {
       "expr": "nebula_storaged_replicate_log_latency_us_p95_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_p95_5"
      }
     ]
    },
    {
     "title": "num_delete_vertices_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_delete_vertices_errors_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_delete_vertices_errors_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "append_log_latency_us",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 106 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "nebula_storaged_append_log_latency_us_avg_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_avg_5"
      },
      {
       "expr": "nebula_storaged_append_log_latency_us_p95_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_p95_5"
      }
     ]
    },
    {
     "title": "num_start_elect",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_start_elect_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_start_elect_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_add_vertices_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 114 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_add_vertices_errors_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_add_vertices_errors_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_add_edges_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_add_edges_errors_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_add_edges_errors_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_add_vertices",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 122 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_add_vertices_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_add_vertices_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "scan_vertex_latency_us",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "nebula_storaged_scan_vertex_latency_us_avg_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_avg_5"
      },
      {
       "expr": "nebula_storaged_scan_vertex_latency_us_p95_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_p95_5"
      }
     ]
    },
    {
     "title": "num_add_edges",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 130 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_add_edges_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_add_edges_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_scan_edge_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_scan_edge_errors_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_scan_edge_errors_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_scan_edge",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 138 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_scan_edge_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_scan_edge_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_kv_remove",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 146 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_kv_remove_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_kv_remove_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "scan_edge_latency_us",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 146 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "nebula_storaged_scan_edge_latency_us_avg_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_avg_5"
      },
      {
       "expr": "nebula_storaged_scan_edge_latency_us_p95_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_p95_5"
      }
     ]
    },
    {
     "title": "num_kv_remove_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 154 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_kv_remove_errors_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_kv_remove_errors_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_kv_put",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 154 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_kv_put_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_kv_put_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_kv_put_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 162 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_kv_put_errors_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_kv_put_errors_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_kv_get",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 162 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_kv_get_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_kv_get_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "kv_remove_latency_us",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 170 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "nebula_storaged_kv_remove_latency_us_avg_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_avg_5"
      },
      {
       "expr": "nebula_storaged_kv_remove_latency_us_p95_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_p95_5"
      }
     ]
    },
    {
     "title": "num_kv_get_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 170 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_kv_get_errors_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_kv_get_errors_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "kv_put_latency_us",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 178 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "nebula_storaged_kv_put_latency_us_avg_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_avg_5"
      },
      {
       "expr": "nebula_storaged_kv_put_latency_us_p95_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_p95_5"
      }
     ]
    },
    {
     "title": "kv_get_latency_us",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 178 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "nebula_storaged_kv_get_latency_us_avg_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_avg_5"
      },
      {
       "expr": "nebula_storaged_kv_get_latency_us_p95_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_p95_5"
      }
     ]
    },
    {
     "title": "num_update_vertex",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 186 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_update_vertex_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_update_vertex_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_update_vertex_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 186 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_update_vertex_errors_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_update_vertex_errors_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_scan_vertex_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 194 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_scan_vertex_errors_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_scan_vertex_errors_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "update_edge_latency_us",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 194 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "nebula_storaged_update_edge_latency_us_avg_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_avg_5"
      },
      {
       "expr": "nebula_storaged_update_edge_latency_us_p95_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_p95_5"
      }
     ]
    },
    {
     "title": "lookup_latency_us",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 202 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "nebula_storaged_lookup_latency_us_avg_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_avg_5"
      },
      {
       "expr": "nebula_storaged_lookup_latency_us_p95_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_p95_5"
      }
     ]
    },
    {
     "title": "num_scan_vertex",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 202 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_scan_vertex_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_scan_vertex_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_tags_deleted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 210 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_tags_deleted_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_tags_deleted_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "transfer_leader_latency_us",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 210 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "nebula_storaged_transfer_leader_latency_us_avg_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_avg_5"
      },
      {
       "expr": "nebula_storaged_transfer_leader_latency_us_p95_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_p95_5"
      }
     ]
    },
    {
     "title": "num_vertices_deleted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 218 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_vertices_deleted_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_vertices_deleted_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_vertices_inserted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 218 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_vertices_inserted_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_vertices_inserted_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_rpc_sent_to_metad_failed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 226 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_rpc_sent_to_metad_failed_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_rpc_sent_to_metad_failed_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_rpc_sent_to_metad",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 226 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_rpc_sent_to_metad_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_rpc_sent_to_metad_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_edges_inserted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 234 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_edges_inserted_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_edges_inserted_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "get_prop_latency_us",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 234 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "nebula_storaged_get_prop_latency_us_avg_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_avg_5"
      },
      {
       "expr": "nebula_storaged_get_prop_latency_us_p95_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_p95_5"
      }
     ]
    },
    {
     "title": "num_get_dst_by_src_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 242 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_get_dst_by_src_errors_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_get_dst_by_src_errors_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_edges_deleted",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 242 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_edges_deleted_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_edges_deleted_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_get_prop",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 250 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_get_prop_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_get_prop_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_get_neighbors_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 250 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_storaged_num_get_neighbors_errors_rate_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_storaged_num_get_neighbors_errors_sum_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "commit_snapshot_latency_us",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 258 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "nebula_storaged_commit_snapshot_latency_us_avg_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_avg_5"
      },
      {
       "expr": "nebula_storaged_commit_snapshot_latency_us_p95_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_p95_5"
      }
     ]
    },
    {
     "title": "get_dst_by_src_latency_us",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 258 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "nebula_storaged_get_dst_by_src_latency_us_avg_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_avg_5"
      },
      {
       "expr": "nebula_storaged_get_dst_by_src_latency_us_p95_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_p95_5"
      }
     ]
    },
    {
     "title": "add_edges_latency_us",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 266 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "nebula_storaged_add_edges_latency_us_avg_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_avg_5"
      },
      {
       "expr": "nebula_storaged_add_edges_latency_us_p95_5{componentType=\"storaged\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_p95_5"
      }
     ]
    }
   ]
  },
  {
   "title": "Nebula Graphd",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "num_queries_hit_memory_watermark",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_graphd_num_queries_hit_memory_watermark_rate_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_graphd_num_queries_hit_memory_watermark_sum_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_active_queries",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_graphd_num_active_queries_sum_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "slow_query_latency_us",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "nebula_graphd_slow_query_latency_us_avg_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_avg_5"
      },
      {
       "expr": "nebula_graphd_slow_query_latency_us_p95_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_p95_5"
      }
     ]
    },
    {
     "title": "num_aggregate_executors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 12 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "nebula_graphd_num_aggregate_executors_rate_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_graphd_num_aggregate_executors_sum_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "optimizer_latency_us",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "nebula_graphd_optimizer_latency_us_avg_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_avg_5"
      },
      {
       "expr": "nebula_graphd_optimizer_latency_us_p95_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_p95_5"
      }
     ]
    },
    {
     "title": "num_auth_failed_sessions_bad_username_password",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_graphd_num_auth_failed_sessions_bad_username_password_rate_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_graphd_num_auth_failed_sessions_bad_username_password_sum_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_sort_executors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "nebula_graphd_num_sort_executors_rate_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_graphd_num_sort_executors_sum_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_auth_failed_sessions_out_of_max_allowed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_graphd_num_auth_failed_sessions_out_of_max_allowed_rate_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_graphd_num_auth_failed_sessions_out_of_max_allowed_sum_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_slow_queries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_graphd_num_slow_queries_rate_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_graphd_num_slow_queries_sum_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_auth_failed_sessions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 36 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_graphd_num_auth_failed_sessions_bad_username_password_rate_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_graphd_num_auth_failed_sessions_bad_username_password_sum_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_sentences",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 43 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_graphd_num_sentences_rate_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_graphd_num_sentences_sum_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "nebula_graphd_num_active_sessions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_graphd_num_active_sessions_sum_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_rpc_sent_to_storaged",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 51 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_graphd_num_rpc_sent_to_storaged_rate_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_graphd_num_rpc_sent_to_storaged_sum_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_killed_queries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_graphd_num_killed_queries_rate_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_graphd_num_killed_queries_sum_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_rpc_sent_to_storaged_failed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_graphd_num_rpc_sent_to_storaged_failed_rate_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_graphd_num_rpc_sent_to_storaged_failed_sum_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_queries",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_graphd_num_queries_rate_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_graphd_num_queries_sum_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_rpc_sent_to_metad",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_graphd_num_rpc_sent_to_metad_rate_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_graphd_num_rpc_sent_to_metad_sum_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_opened_sessions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_graphd_num_opened_sessions_rate_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_graphd_num_opened_sessions_sum_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_rpc_sent_to_metad_failed",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 75 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_graphd_num_rpc_sent_to_metad_failed_rate_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_graphd_num_rpc_sent_to_metad_failed_sum_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "query_latency_us",
     "type": "timeseries",
     "gridPos": { "h": 9, "w": 12, "x": 12, "y": 76 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "nebula_graphd_query_latency_us_avg_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_avg_5"
      },
      {
       "expr": "nebula_graphd_query_latency_us_p95_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_p95_5"
      }
     ]
    },
    {
     "title": "num_reclaimed_expired_sessions",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 83 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_graphd_num_reclaimed_expired_sessions_rate_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_graphd_num_reclaimed_expired_sessions_sum_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_query_errors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 85 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_graphd_num_query_errors_rate_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_graphd_num_query_errors_sum_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_query_errors_leader_changes",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 91 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "nebula_graphd_num_query_errors_leader_changes_rate_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_graphd_num_query_errors_leader_changes_sum_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    },
    {
     "title": "num_indexscan_executors",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 93 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "expr": "nebula_graphd_num_indexscan_executors_rate_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_rate_5"
      },
      {
       "expr": "nebula_graphd_num_indexscan_executors_sum_5{componentType=\"graphd\", nebula_cluster=\"$cluster_id\"}",
       "legendFormat": "{{instanceName}}_sum_5"
      }
     ]
    }
   ]
  }
 ]
}