{
 "title": "nebula",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Number Of Metad Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(nebula_metad_count)" }
   ]
  },
  {
   "title": "Number Of Graphd Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 8, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(nebula_graphd_count)" }
   ]
  },
  {
   "title": "Number Of Storaged Nodes",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 8, "x": 16, "y": 0 },
   "format": "none",
   "valueName": "current",
   "targets": [
    { "expr": "sum(nebula_storaged_count)" }
   ]
  },
  {
   "title": "Slow Query Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_slow_query_latency_us_avg_5"
    },
    {
     "expr": "nebula_graphd_slow_query_latency_us_p95_5"
    }
   ]
  },
  {
   "title": "Query Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_query_latency_us_avg_5"
    },
    {
     "expr": "nebula_graphd_query_latency_us_p95_5"
    }
   ]
  },
  {
   "title": "Number Query Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_num_query_errors_rate_60"
    },
    {
     "expr": "nebula_graphd_num_query_errors_sum_60"
    }
   ]
  },
  {
   "title": "Number  Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_num_queries_rate_5"
    },
    {
     "expr": "nebula_graphd_num_queries_sum_5"
    }
   ]
  },
  {
   "title": "Number Slow Queries",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "nebula_graphd_num_slow_queries_rate_5"
    },
    {
     "expr": "nebula_graphd_num_slow_queries_sum_5"
    }
   ]
  }
 ]
}